spring:
  #h2:
    #console:
      #enabled: true
      #path: /h2-console
  #jpa:
    #show-sql: true
#spring:
  datasource:
    url: jdbc:mysql://localhost:3306/utnphones
    username: root
    password:
  jpa:
    hibernate:
      generate-ddl: false